---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: debezium/postgres:11
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
               secretKeyRef:
                 key: pgsql_postgres_password
                 name: psql-env
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: pgsql_username
                  name: psql-env
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: pgsql_db
                  name: psql-env