apiVersion: v1
kind: Service
metadata:
  labels:
    app: apicurio-registry
  name: apicurio-registry
spec:
  ports:
  - name: 8080-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: apicurio-registry
    deploymentconfig: apicurio-registry
  type: LoadBalancer

